/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Principal;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public String getGreeting2() {
        return "Fala fio!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getGreeting2());
    }
}
