/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProg;

public class App {
    
    public static void main(String[] args) {
        float numero;
        numero =10.5f;
        System.out.println("Valor de numero é: " + numero);
    }
}
